service: dio-live-serverless-project

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iam:
    role:
        statements:
          - Effect: Allow
            Actions:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:GetItem
              - dynamodb:scan
            Resource:
              - arn:aws:dynamodb-us-east-1:idDaConta:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    event:
      - http:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    event:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    event:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: src/fetchItem.handler
    event:
      - http:
          path: /item/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    event:
      - http:
          path: /items/{id}
          method: put

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
